### ISSUE TITLE
Test/loading

### ISSUE THREAD

**Issue by NeoDigi** [benoitletondor/Beer-Me-Up#2]
Hey thank you for this app, this is awesome, I'm using it as kind of a template for an app of my own.

I was wondering if you intended to make some test for it?

Also I realized something is that firebase is supposed to work offline too but in your current implementation it doesn't, and for the user experience it'd be awesome to have that.
I don't know if it's currently possible with the current state of flutter but for example your loading all data in the loading state Everytime and I think that the data already on the device should be already displayed even during the loading state.
To be honest I did try to do just that but couldn't make it work so I was wondering if you had any idea or if you also intended to implement it latter?

Ok really nice work so far

**Comment by benoitletondor** [comment]
Hi @NeoDigi !

About tests:
- The MVI architecture extract the logic into models which are highly testable since they are pure dart without any Flutter related stuff, and you can easily mock services to test behaviour
- I didn't try to write any UI test so I can't help you with that

About offline firestore: Yes offline doesn't seem to work right now, maybe an issue with firestore client? To be honest it wasn't really important for my app as it would still depend on network for beer list fetch so I didn't try very hard. Let me know if you make some progress on that point.

Thank you again for your nice words, appreciate it :)
